dist: trusty
sudo: false
language: python

before_install:
  - '[ "$TEST_PEP8" == "1" ] || sudo ./tests/test_env/deploy.sh'

python:
  - "2.7"

install: 
  - pip install -e .
  - "if [[ $TEST_PEP8 == '1' ]]; then pip install pep8; fi"
  - pip install coveralls

# command to run tests
script: "if [[ $TEST_PEP8 == '1' ]]; then pep8 --repeat --show-source --exclude=.venv,.tox,dist,docs,build,*.egg,tests,misc . scripts/*; else coverage run --source=kerinou setup.py test; fi"
matrix:
  include:
    - python: "2.7"
      env: TEST_PEP8=1
    - python: "2.7"
      env: Unit tests

after_success:
  - coveralls
